/**
 * File extension mappings and classification
 */

import type { FileTier } from "../types/index.js";

/** Mapping of extensions to their processing tier */
export const EXTENSION_TIER_MAP: Record<string, FileTier> = {
  // Tier 1: Passthrough (text-based, wrapped in Markdown)
  // Plain text
  txt: "passthrough",
  // Markdown
  md: "passthrough",
  mdx: "passthrough",
  // Data formats
  json: "passthrough",
  yaml: "passthrough",
  yml: "passthrough",
  xml: "passthrough",
  csv: "passthrough",
  tsv: "passthrough",
  // Config files
  ini: "passthrough",
  toml: "passthrough",
  env: "passthrough",
  conf: "passthrough",
  cfg: "passthrough",
  // Code files
  py: "passthrough",
  js: "passthrough",
  ts: "passthrough",
  jsx: "passthrough",
  tsx: "passthrough",
  go: "passthrough",
  rs: "passthrough",
  java: "passthrough",
  c: "passthrough",
  cpp: "passthrough",
  h: "passthrough",
  hpp: "passthrough",
  rb: "passthrough",
  php: "passthrough",
  swift: "passthrough",
  kt: "passthrough",
  sql: "passthrough",
  sh: "passthrough",
  bash: "passthrough",
  zsh: "passthrough",
  ps1: "passthrough",
  r: "passthrough",
  scala: "passthrough",
  lua: "passthrough",
  pl: "passthrough",
  m: "passthrough",
  css: "passthrough",
  scss: "passthrough",
  sass: "passthrough",
  less: "passthrough",

  // Tier 2: Conversion required
  pdf: "conversion",
  docx: "conversion",
  doc: "conversion",
  xlsx: "conversion",
  xls: "conversion",
  pptx: "conversion",
  ppt: "conversion",
  html: "conversion",
  htm: "conversion",
  rtf: "conversion",
  epub: "conversion",

  // Tier 3: OCR required
  png: "ocr",
  jpg: "ocr",
  jpeg: "ocr",
  gif: "ocr",
  webp: "ocr",
  tiff: "ocr",
  tif: "ocr",
  bmp: "ocr",
};

/** Extensions that are code files (for syntax highlighting hints) */
export const CODE_EXTENSIONS = new Set([
  "py",
  "js",
  "ts",
  "jsx",
  "tsx",
  "go",
  "rs",
  "java",
  "c",
  "cpp",
  "h",
  "hpp",
  "rb",
  "php",
  "swift",
  "kt",
  "sql",
  "sh",
  "bash",
  "zsh",
  "ps1",
  "r",
  "scala",
  "lua",
  "pl",
  "m",
  "css",
  "scss",
  "sass",
  "less",
]);

/** Language hints for code block syntax highlighting */
export const EXTENSION_LANGUAGE_MAP: Record<string, string> = {
  py: "python",
  js: "javascript",
  ts: "typescript",
  jsx: "jsx",
  tsx: "tsx",
  go: "go",
  rs: "rust",
  java: "java",
  c: "c",
  cpp: "cpp",
  h: "c",
  hpp: "cpp",
  rb: "ruby",
  php: "php",
  swift: "swift",
  kt: "kotlin",
  sql: "sql",
  sh: "bash",
  bash: "bash",
  zsh: "zsh",
  ps1: "powershell",
  r: "r",
  scala: "scala",
  lua: "lua",
  pl: "perl",
  m: "matlab",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  html: "html",
  htm: "html",
  md: "markdown",
  mdx: "mdx",
  toml: "toml",
  ini: "ini",
};

/** Data format extensions (for special handling) */
export const DATA_EXTENSIONS = new Set([
  "json",
  "yaml",
  "yml",
  "xml",
  "csv",
  "tsv",
]);

/** Binary/unsupported extensions */
export const BINARY_EXTENSIONS = new Set([
  "exe",
  "dll",
  "so",
  "dylib",
  "bin",
  "o",
  "obj",
  "class",
  "pyc",
  "pyo",
  "wasm",
  "zip",
  "tar",
  "gz",
  "rar",
  "7z",
  "iso",
  "dmg",
  "mp3",
  "wav",
  "m4a",
  "ogg",
  "flac",
  "mp4",
  "mov",
  "avi",
  "mkv",
  "webm",
]);
