/**
 * Failures reporter
 * Generates FAILURES.md with detailed failure information
 */

import type { FailedFile, ProcessingPlan } from "../types/index.js";

/**
 * Generate the failures report content
 */
export function generateFailuresReport(
  failures: FailedFile[],
  _plan?: ProcessingPlan
): string {
  if (failures.length === 0) {
    return generateEmptyReport();
  }

  const lines: string[] = [];

  // Header
  lines.push("# Processing Failures Report");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Total failures: ${failures.length}`);
  lines.push("");

  // Summary by error type
  lines.push("## Summary by Error Type");
  lines.push("");

  const byError = groupByErrorCode(failures);
  lines.push("| Error Type | Count |");
  lines.push("|------------|-------|");

  for (const [code, files] of Object.entries(byError)) {
    lines.push(`| ${formatErrorCode(code)} | ${files.length} |`);
  }

  lines.push("");

  // Detailed failures
  lines.push("## Detailed Failures");
  lines.push("");

  for (const failure of failures) {
    lines.push(`### ${failure.originalPath}`);
    lines.push("");
    lines.push(`- **Reason**: ${failure.reason}`);
    lines.push(`- **Error Code**: \`${failure.errorCode}\``);
    lines.push(`- **Original Preserved**: ${failure.copied ? "Yes" : "No"}`);
    lines.push("");
  }

  // Suggestions
  lines.push("## Suggested Actions");
  lines.push("");
  lines.push(generateSuggestions(failures));

  // Footer
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("*The original files have been copied to this folder for your reference.*");

  return lines.join("\n");
}

/**
 * Generate empty report when no failures
 */
function generateEmptyReport(): string {
  return `# Processing Failures Report

Generated: ${new Date().toISOString()}

## No Failures

All files were processed successfully! 🎉

---

*Generated by Flatpack*
`;
}

/**
 * Group failures by error code
 */
function groupByErrorCode(
  failures: FailedFile[]
): Record<string, FailedFile[]> {
  const groups: Record<string, FailedFile[]> = {};

  for (const failure of failures) {
    const code = failure.errorCode;
    if (!groups[code]) {
      groups[code] = [];
    }
    groups[code]!.push(failure);
  }

  return groups;
}

/**
 * Format error code for display
 */
function formatErrorCode(code: string): string {
  return code
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
}

/**
 * Generate suggestions based on failure types
 */
function generateSuggestions(failures: FailedFile[]): string {
  const suggestions: string[] = [];
  const codes = new Set(failures.map((f) => f.errorCode));

  if (codes.has("COPY_PROTECTED") || codes.has("PERMISSION_DENIED")) {
    suggestions.push(
      "- **Copy-protected files**: Try opening the PDF in a viewer and re-saving without protection"
    );
  }

  if (codes.has("UNSUPPORTED_FORMAT")) {
    suggestions.push(
      "- **Unsupported formats**: Convert these files to a supported format (PDF, DOCX, TXT, MD) before processing"
    );
  }

  if (codes.has("ENCODING_ERROR")) {
    suggestions.push(
      "- **Encoding issues**: Try re-saving the file with UTF-8 encoding"
    );
  }

  if (codes.has("OCR_FAILED")) {
    suggestions.push(
      "- **OCR failures**: Ensure images are clear and text is readable. Try improving image quality."
    );
  }

  if (codes.has("CORRUPTED_FILE")) {
    suggestions.push(
      "- **Corrupted files**: Try obtaining a fresh copy of the file"
    );
  }

  if (codes.has("CONVERSION_FAILED")) {
    suggestions.push(
      "- **Conversion failures**: Try opening and re-saving the file in its native application"
    );
  }

  if (suggestions.length === 0) {
    suggestions.push(
      "- Review the error details above and try processing the files individually"
    );
  }

  return suggestions.join("\n");
}

/**
 * Create failed file records from processing plan
 */
export function createFailedFileRecords(
  plan: ProcessingPlan,
  errors: Map<string, string>
): FailedFile[] {
  const failures: FailedFile[] = [];

  // From skipped files
  for (const skipped of plan.skipped) {
    failures.push({
      originalPath: skipped.source.relativePath,
      reason: skipped.source.warnings[0]?.message || "Unsupported format",
      errorCode: skipped.source.warnings[0]?.code || "UNSUPPORTED_FORMAT",
      copied: true,
    });
  }

  // From processing errors
  for (const [path, error] of errors) {
    failures.push({
      originalPath: path,
      reason: error,
      errorCode: inferErrorCode(error),
      copied: true,
    });
  }

  return failures;
}

/**
 * Infer error code from error message
 */
function inferErrorCode(message: string): string {
  const lower = message.toLowerCase();

  if (lower.includes("protected") || lower.includes("encrypted")) {
    return "COPY_PROTECTED";
  }
  if (lower.includes("permission")) {
    return "PERMISSION_DENIED";
  }
  if (lower.includes("encoding")) {
    return "ENCODING_ERROR";
  }
  if (lower.includes("ocr")) {
    return "OCR_FAILED";
  }
  if (lower.includes("corrupt")) {
    return "CORRUPTED_FILE";
  }
  if (lower.includes("conversion") || lower.includes("convert")) {
    return "CONVERSION_FAILED";
  }
  if (lower.includes("unsupported")) {
    return "UNSUPPORTED_FORMAT";
  }

  return "UNKNOWN";
}

/**
 * Get failure statistics
 */
export function getFailureStats(failures: FailedFile[]): {
  total: number;
  byCode: Record<string, number>;
  copiedCount: number;
} {
  const byCode: Record<string, number> = {};
  let copiedCount = 0;

  for (const failure of failures) {
    byCode[failure.errorCode] = (byCode[failure.errorCode] || 0) + 1;
    if (failure.copied) copiedCount++;
  }

  return {
    total: failures.length,
    byCode,
    copiedCount,
  };
}
