/**
 * Structure generator
 * Creates 00_MASTER_STRUCTURE.md with directory tree and summary
 */

import type { ProcessingPlan, FlatpackConfig, FlatpackManifest } from "../types/index.js";
import { formatNumber, formatDuration } from "../utils/index.js";

/**
 * Generate the master structure file content
 */
export function generateMasterStructure(
  plan: ProcessingPlan,
  config: FlatpackConfig,
  manifest?: FlatpackManifest
): string {
  const lines: string[] = [];

  // Header
  lines.push("# Flatpack Master Structure");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push(`Tier: ${config.tier.toUpperCase()}`);
  lines.push("");

  // Summary statistics
  lines.push("## Summary");
  lines.push("");

  if (manifest) {
    lines.push(`- **Input files**: ${formatNumber(manifest.summary.totalInputFiles)}`);
    lines.push(`- **Output files**: ${formatNumber(manifest.summary.totalOutputFiles)}`);
    lines.push(`- **Total words**: ${formatNumber(manifest.summary.totalWordCount)}`);
    lines.push(`- **Processing time**: ${formatDuration(manifest.summary.processingDuration)}`);
  } else {
    lines.push(`- **Planned files**: ${formatNumber(plan.files.length)}`);
    lines.push(`- **Estimated output**: ${formatNumber(plan.summary.totalOutputFiles)}`);
    lines.push(`- **Estimated words**: ${formatNumber(plan.summary.totalWordCount)}`);
  }

  lines.push("");

  // Action breakdown
  lines.push("## Processing Actions");
  lines.push("");
  lines.push("| Action | Count |");
  lines.push("|--------|-------|");

  const actions = manifest
    ? [
        ["Passed through", manifest.summary.passedThrough],
        ["Converted", manifest.summary.converted],
        ["Chunked", manifest.summary.chunked],
        ["Merged", manifest.summary.merged],
        ["OCR'd", manifest.summary.ocrd],
        ["Failed", manifest.summary.failed],
      ]
    : Object.entries(plan.summary.byAction).filter(([_, count]) => count > 0);

  for (const [action, count] of actions) {
    if (typeof count === "number" && count > 0) {
      lines.push(`| ${action} | ${count} |`);
    }
  }

  lines.push("");

  // Directory tree
  lines.push("## Original Directory Structure");
  lines.push("");
  lines.push("```");
  lines.push(generateTreeOutput(plan));
  lines.push("```");
  lines.push("");

  // Output file listing
  lines.push("## Output Files");
  lines.push("");

  // Group by action
  const byAction = groupByAction(plan);

  for (const [action, files] of Object.entries(byAction)) {
    if (files.length === 0) continue;

    lines.push(`### ${formatActionTitle(action)} (${files.length})`);
    lines.push("");

    for (const file of files.slice(0, 50)) {
      // Limit display
      const words = formatNumber(file.source.wordCount);
      lines.push(`- \`${file.outputName}\` (${words} words)`);
      lines.push(`  - Source: ${file.source.relativePath}`);
    }

    if (files.length > 50) {
      lines.push(`- ... and ${files.length - 50} more`);
    }

    lines.push("");
  }

  // Bundles section
  if (plan.bundles.length > 0) {
    lines.push("## Bundles");
    lines.push("");

    for (const bundle of plan.bundles) {
      lines.push(`### ${bundle.outputName}`);
      lines.push("");
      lines.push(`- **Folder**: ${bundle.folderPath || "(root)"}`);
      lines.push(`- **Files**: ${bundle.files.length}`);
      lines.push(`- **Total words**: ${formatNumber(bundle.totalWordCount)}`);
      lines.push("");
      lines.push("Contains:");
      for (const file of bundle.files.slice(0, 20)) {
        lines.push(`- ${file.source.relativePath}`);
      }
      if (bundle.files.length > 20) {
        lines.push(`- ... and ${bundle.files.length - 20} more`);
      }
      lines.push("");
    }
  }

  // Warnings section
  if (plan.warnings.length > 0) {
    lines.push("## Warnings");
    lines.push("");

    for (const warning of plan.warnings) {
      lines.push(`- ⚠️ ${warning.message}`);
    }

    lines.push("");
  }

  // Failed files section
  if (plan.skipped.length > 0) {
    lines.push("## Failed/Skipped Files");
    lines.push("");

    for (const file of plan.skipped) {
      const reason =
        file.source.warnings[0]?.message || "Unsupported format";
      lines.push(`- \`${file.source.relativePath}\`: ${reason}`);
    }

    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("*Generated by Flatpack*");

  return lines.join("\n");
}

/**
 * Generate tree output for directory structure
 */
export function generateTreeOutput(plan: ProcessingPlan): string {
  const paths = plan.files.map((f) => f.source.relativePath);
  return buildTree(paths);
}

/**
 * Build a text tree from paths
 */
function buildTree(paths: string[]): string {
  interface TreeNode {
    name: string;
    children: Map<string, TreeNode>;
    isFile: boolean;
  }

  const root: TreeNode = { name: "", children: new Map(), isFile: false };

  // Build tree structure
  for (const path of paths) {
    const parts = path.split("/");
    let current = root;

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i]!;
      const isFile = i === parts.length - 1;

      if (!current.children.has(part)) {
        current.children.set(part, {
          name: part,
          children: new Map(),
          isFile,
        });
      }

      current = current.children.get(part)!;
    }
  }

  // Render tree
  const lines: string[] = [];

  function render(node: TreeNode, prefix: string, isLast: boolean): void {
    if (node.name) {
      const connector = isLast ? "└── " : "├── ";
      const icon = node.isFile ? "" : "📁 ";
      lines.push(prefix + connector + icon + node.name);
    }

    const children = Array.from(node.children.values()).sort((a, b) => {
      // Directories first, then files
      if (a.isFile !== b.isFile) return a.isFile ? 1 : -1;
      return a.name.localeCompare(b.name);
    });

    for (let i = 0; i < children.length; i++) {
      const child = children[i]!;
      const newPrefix = node.name
        ? prefix + (isLast ? "    " : "│   ")
        : prefix;
      render(child, newPrefix, i === children.length - 1);
    }
  }

  render(root, "", true);

  return lines.join("\n");
}

/**
 * Group planned files by action
 */
function groupByAction(
  plan: ProcessingPlan
): Record<string, typeof plan.files> {
  const groups: Record<string, typeof plan.files> = {};

  for (const file of plan.files) {
    const action = file.action;
    if (!groups[action]) {
      groups[action] = [];
    }
    groups[action]!.push(file);
  }

  return groups;
}

/**
 * Format action name for display
 */
function formatActionTitle(action: string): string {
  switch (action) {
    case "keep":
      return "Passed Through";
    case "convert":
      return "Converted";
    case "chunk":
      return "Chunked";
    case "merge":
      return "Merged";
    case "ocr":
      return "OCR Processed";
    case "skip":
    case "fail":
      return "Failed/Skipped";
    default:
      return action.charAt(0).toUpperCase() + action.slice(1);
  }
}
